# Generated by Django 2.0 on 2017-12-26 02:44

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_signin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='signin',
            unique_together={('event', 'user')},
        ),
    ]
